version: 0.2

phases:
  install:
    commands:

  build:
    commands:
      - pip install taskcat
      - taskcat -c ci/taskcat.yml

artifacts:
  type: CODEPIPELINE
  files:
    - '**/*'
#  discard-paths: no
#  base-directory: location
