version: 0.2

phases:

  pre_build:
    commands:
      - stackname=$(echo $CODEBUILD_INITIATOR |cut -d/ -f2)-Replica
      - v_repo=$(echo $CODEBUILD_INITIATOR |cut -d/ -f2)
      - v_repomaster=$(aws codecommit list-branches --repository-name $v_repo |grep master |uniq |wc -l |xargs)

  build:
    commands:
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
      - if [ $v_repomaster -eq 0 ]; then git clone https://git-codecommit.$AWS_REGION.amazonaws.com/v1/repos/$v_repo branch-master; cd branch-master; git add *; git commit -m "First Commit"; git push origin master;fi
      - if [ $v_repomaster -gt 0 ]; then git clone --branch master https://git-codecommit.$AWS_REGION.amazonaws.com/v1/repos/$v_repo branch-master; cd branch-master; fi
      - if aws cloudformation describe-stacks --stack-name $stackname; then aws cloudformation delete-stack --stack-name $stackname; aws cloudformation wait stack-delete-complete --stack-name $stackname; fi
      - aws cloudformation create-stack --stack-name $stackname --template-body file://templates/$TEMPLATE
      - aws cloudformation wait stack-create-complete --stack-name $stackname || exit 0